### ISSUE TITLE
Andrea Panuccio (s294603) LAB2 "Nim w ES" Pair Review 

### ISSUE THREAD

**Issue by AndPan96** [baraccothomas/computational-intelligence#1]
**Review of lab2-nim.ipynb**
Hi, there's a friendly feedback here! 
I've read your notebook and I've found your solution quite fashinating. Overall I appreciated:

- The model you've chosen: it's just a step behind to Genetic Programming, just for the fact that genotypes have a fixed size, but it has a lot of potential. For what I got, it learns fixed size criteria and selects the ones that happen to lead to a higher winrate. 
- The code design was quite clever too: you optimized a lot of operations, both sintactically and computationally, taking advantage of the fixed size of your criteria domain / genome.

Now I take the burden of suggesting some friendly tips that I hope will be helpful to make your future work better:

- I would have appreciated some more general comments in the most structured functions, especially about the meaning of the elements of the model you have chosen. It wasn't that hard thanks to the quite clear code, but I had to figure it out on my own.
- I also wanted to read about your choices regarding the problem, your model, your design and your final result and conclusions. The solution is really clever but I can barely imagine your thought process.

Best regards, 
Andrea Panuccio

**Comment by baraccothomas** [comment]
Thanks for the feedback both positive and negative! I will surely add more comments on my code, I agree that it can be hard to understand. I will also check the algorithm that, since was a bit complicated to implement, can contain some mistakes or differences from the optimal strategy that should be used.
